<!DOCTYPE html>  
<html lang="en">  
    <head>
        <meta charset="UTF-8">
        <title>Goldeneye</title>
    </head>
    <body>
        <h1>New Employee Details</h1>

        Name: ${employee.name}<br/>
        Surname: ${employee.surname}<br/>
        Office: ${employee.office}<br/>
        Deparment: ${employee.department}<br/>
        Email: ${employee.email}<br/>

    </body>
</html>